<!-- Generated by figma2htmlv1.0.0-beta on 2023-04-12 18:34 -->
<script>
  import { onMount } from "svelte";
  onMount(() => {
    ((e) => {
      if (!("querySelector" in document)) return;
      const t = (e) => {
          const t = e.getAttribute("data-src");
          t && e.getAttribute("src") != t && e.setAttribute("src", t);
        },
        n = (e) => {
          e.reduce((e, t) => e || t.isIntersecting, !1) && ((c = !1), r());
        },
        i = (e, t) =>
          t ? Array.prototype.slice.call(t.querySelectorAll(e)) : [],
        r = () => {
          const e = i(
              `.${s}artboard:where([data-min-width],[data-max-width])`,
              o
            ),
            a = Math.min(Math.round(o.offsetWidth), window.innerWidth);
          e.forEach(function (e) {
            const n = e.getAttribute("data-min-width"),
              r = e.getAttribute("data-max-width");
            +n <= a && (+r >= a || null === r)
              ? (c || i(`.${s}f2h-img`, e).forEach(t),
                (e.style.display = "block"))
              : (e.style.display = "none");
          }),
            c &&
              !l &&
              (((e) => {
                const t = e.getBoundingClientRect();
                return t.top < window.innerHeight && t.bottom > 0;
              })(o)
                ? ((c = !1), r())
                : ((l = new IntersectionObserver(n, {
                    rootMargin: "400px 400px",
                  })),
                  l.observe(o)));
        },
        o = document.getElementById(e),
        a = ((e, t) => {
          let n = null,
            i = 0;
          const r = () => {
            (i = Date.now()), (n = null), e();
          };
          return function () {
            const e = t - (Date.now() - i);
            e <= 0 || e > t
              ? (clearTimeout(n), r())
              : n || (n = setTimeout(r, e));
          };
        })(r, 200),
        s = "";
      let l,
        c = !!window.IntersectionObserver;
      r(),
        document.addEventListener("DOMContentLoaded", r),
        window.addEventListener("resize", a);
    })("demo-box", {
      namespace: "",
      setup: window.setupInteractive || window.getComponent,
    });
    const apiLink = document.createElement("link");
    apiLink.rel = "preconnect";
    apiLink.href = "https://fonts.googleapis.com";

    const gstaticLink = document.createElement("link");
    gstaticLink.rel = "preconnect";
    gstaticLink.href = "https://fonts.gstatic.com";
    gstaticLink.crossorigin = true;

    const fontLink = document.createElement("link");
    fontLink.rel = "stylesheet";
    fontLink.href =
      "https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,700;0,800&display=swap";

    document.head.appendChild(apiLink);
    document.head.appendChild(gstaticLink);
    document.head.appendChild(fontLink);
  });
</script>

<div id="demo-box" class="figma2html">
  <!-- Frame: 960px -->
  <div
    id="f2h-frame-960"
    class="f2h-frame frame artboard"
    data-aspect-ratio="1.373"
    data-min-width="960"
  >
    <div
      class="spacer"
      style="padding: 0 0 0 0; min-width: 960px; max-width: none;"
    />
    <picture>
      <img
        id="img-f2h-frame-960"
        class="f2h-img"
        alt="voters turnout over the years"
        src="figma2html/960px.png"
        loading="lazy"
        draggable="false"
        decoding="async"
        width="960.00"
        height="699.00"
      />
    </picture>
    <div
      class="f2h-text"
      style="top: 4.82% ; left: 49.95% ; opacity: 1; width: 611.34px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-0">
        <span style="font-weight: 800"
          >2023 Voters Participation Rate was the lowest since 1999</span
        >
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 26.56% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-1"><b>1999</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 68.70% ; left: 20.06% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-2"><b>20%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 55.09% ; left: 20.06% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-3"><b>40%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 41.48% ; left: 20.06% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-4"><b>60%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 27.65% ; left: 20.06% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-5"><b>80%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 18.65% ; left: 69.45% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-6"><b>Participation Rate by Registered Voters</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 18.65% ; left: 32.43% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-7">
        <b>Participation Rate by Voting Age Population </b>
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 35.23% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-8"><b>2003</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 43.89% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-9"><b>2007</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 52.55% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-10"><b>2011</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 61.21% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-11"><b>2015</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 69.88% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-12"><b>2019</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 78.54% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-13"><b>2023</b></p>
    </div>
  </div>

  <!-- Frame: 640px -->
  <div
    id="f2h-frame-640"
    class="f2h-frame frame artboard"
    data-aspect-ratio="1.37"
    data-min-width="640"
    data-max-width="959"
  >
    <div
      class="spacer"
      style="padding: 0 0 0 0; min-width: 640px; max-width: 959px;"
    />
    <picture>
      <img
        id="img-f2h-frame-640"
        class="f2h-img"
        alt="voters turnout over the years"
        src="figma2html/640px.png"
        loading="lazy"
        draggable="false"
        decoding="async"
        width="640.00"
        height="467.00"
      />
    </picture>
    <div
      class="f2h-text"
      style="top: 4.82% ; left: 50.05% ; opacity: 1; width: 408.44px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-0">
        <span style="font-weight: 800"
          >2023 Voters Participation Rate was the lowest since 1999</span
        >
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 26.67% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-1"><b>1999</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 68.70% ; left: 20.10% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-2"><b>20%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 55.09% ; left: 20.10% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-3"><b>40%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 41.48% ; left: 20.10% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-4"><b>60%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 27.65% ; left: 20.10% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-5"><b>80%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 18.65% ; left: 69.59% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-6"><b>Participation Rate by Registered Voters</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 18.65% ; left: 32.52% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-7">
        <b>Participation Rate by Voting Age Population </b>
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 35.35% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-8"><b>2003</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 44.03% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-9"><b>2007</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 52.71% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-10"><b>2011</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 61.39% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-11"><b>2015</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 70.07% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-12"><b>2019</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 87.46% ; left: 78.75% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-13"><b>2023</b></p>
    </div>
  </div>

  <!-- Frame: 555px -->
  <div
    id="f2h-frame-555"
    class="f2h-frame frame artboard"
    data-aspect-ratio="1.37"
    data-min-width="555"
    data-max-width="639"
  >
    <div
      class="spacer"
      style="padding: 0 0 0 0; min-width: 555px; max-width: 639px;"
    />
    <picture>
      <img
        id="img-f2h-frame-555"
        class="f2h-img"
        alt="voters turnout over the years"
        src="figma2html/555px.png"
        loading="lazy"
        draggable="false"
        decoding="async"
        width="555.00"
        height="405.00"
      />
    </picture>
    <div
      class="f2h-text"
      style="top: 5.93% ; left: 50.09% ; opacity: 1; width: 470.00px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-0">
        <span style="font-weight: 800"
          >2023 Voters Participation Rate was the lowest since 1999</span
        >
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 20.63% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-1"><b>1999</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 71.86% ; left: 13.33% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-2"><b>20%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 56.79% ; left: 13.33% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-3"><b>40%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 41.72% ; left: 13.33% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-4"><b>60%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 26.42% ; left: 13.33% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-5"><b>80%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 15.80% ; left: 72.69% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-6"><b>Participation Rate by Registered Voters</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 15.80% ; left: 29.82% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-7">
        <b>Participation Rate by Voting Age Population </b>
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 30.24% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-8"><b>2003</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 39.85% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-9"><b>2007</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 49.46% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-10"><b>2011</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 59.07% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-11"><b>2015</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 68.68% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-12"><b>2019</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 78.29% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-13"><b>2023</b></p>
    </div>
  </div>

  <!-- Frame: 300px -->
  <div
    id="f2h-frame-300"
    class="f2h-frame frame artboard"
    data-aspect-ratio="1.33"
    data-max-width="554"
  >
    <div
      class="spacer"
      style="padding: 0 0 0 0; min-width: 300px; max-width: 554px;"
    />
    <picture>
      <img
        id="img-f2h-frame-300"
        class="f2h-img"
        alt="voters turnout over the years"
        src="figma2html/300px.png"
        loading="lazy"
        draggable="false"
        decoding="async"
        width="300.00"
        height="225.49"
      />
    </picture>
    <div
      class="f2h-text"
      style="top: 5.93% ; left: 51.59% ; opacity: 1; width: 261.68px; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-0">
        <span style="font-weight: 800"
          >2023 Voters Participation Rate was the lowest since 1999</span
        >
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 21.21% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-1"><b>1999</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 71.86% ; left: 13.76% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-2"><b>20%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 56.79% ; left: 13.76% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-3"><b>40%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 41.72% ; left: 13.76% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-4"><b>60%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 26.42% ; left: 13.76% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-5"><b>80%</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 15.80% ; left: 74.88% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-6"><b>Participation Rate by Registered Voters</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 15.80% ; left: 30.74% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-7">
        <b>Participation Rate by Voting Age Population </b>
      </p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 31.10% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-8"><b>2003</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 41.00% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-9"><b>2007</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 50.90% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-10"><b>2011</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 60.80% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-11"><b>2015</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 70.69% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-12"><b>2019</b></p>
    </div>
    <div
      class="f2h-text"
      style="top: 92.62% ; left: 80.59% ; opacity: 1; width: auto; transform: translate(-50%, 0%) rotate(0deg); transform-origin: left top; text-align: center; "
    >
      <p class="f2h-text-13"><b>2023</b></p>
    </div>
  </div>
</div>

<!-- End figma2htmlv1.0.0-beta generated content - 2023-04-12 18:34 -->

<style>
  #demo-box {
    max-width: none;
    margin: 0;
  }

  #demo-box p,
  #demo-box .body {
    margin: 0;
  }

  #demo-box .f2h-img {
    width: 100% !important;
    top: 0;
  }

  #demo-box .f2h-symbol {
    box-sizing: border-box;
  }

  #demo-box :where(.frame, .f2h-text, .f2h-symbol) {
    position: absolute;
  }

  #demo-box :where(.f2h-link, .f2h-img) {
    display: block;
  }

  #f2h-frame-960 {
    position: relative;
    overflow: hidden;
    display: none;
  }

  #f2h-frame-960 p {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 20.228294372558594px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-0 {
    font-family: Lato;
    font-style: normal;
    font-weight: 800;
    font-size: 30.567201614379883px;
    text-decoration: none;
    text-transform: none;
    line-height: normal;
    letter-spacing: 0px;
    color: rgba(0, 0, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-2 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 17.9807071685791px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-3 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 17.9807071685791px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-4 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 17.9807071685791px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-5 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 17.9807071685791px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-6 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 17.9807071685791px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(124, 155, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-960 .f2h-text-7 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 17.9807071685791px;
    text-decoration: none;
    text-transform: none;
    line-height: 26.371700286865234px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }

  #f2h-frame-640 {
    position: relative;
    overflow: hidden;
    display: none;
  }

  #f2h-frame-640 p {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 13.5144681930542px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-0 {
    font-family: Lato;
    font-style: normal;
    font-weight: 800;
    font-size: 20.421863555908203px;
    text-decoration: none;
    text-transform: none;
    line-height: normal;
    letter-spacing: 0px;
    color: rgba(0, 0, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-2 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.012861251831055px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-3 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.012861251831055px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-4 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.012861251831055px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-5 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.012861251831055px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-6 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.012861251831055px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(124, 155, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-640 .f2h-text-7 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.012861251831055px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.618860244750977px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }

  #f2h-frame-555 {
    position: relative;
    overflow: hidden;
    display: none;
  }

  #f2h-frame-555 p {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.972410202026367px;
    text-decoration: none;
    text-transform: none;
    line-height: 16.91217803955078px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-0 {
    font-family: Lato;
    font-style: normal;
    font-weight: 800;
    font-size: 17.710609436035156px;
    text-decoration: none;
    text-transform: none;
    line-height: normal;
    letter-spacing: 0px;
    color: rgba(0, 0, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-2 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 11.531031608581543px;
    text-decoration: none;
    text-transform: none;
    line-height: 16.91217803955078px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-3 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 11.531031608581543px;
    text-decoration: none;
    text-transform: none;
    line-height: 16.91217803955078px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-4 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 11.531031608581543px;
    text-decoration: none;
    text-transform: none;
    line-height: 16.91217803955078px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-5 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 11.531031608581543px;
    text-decoration: none;
    text-transform: none;
    line-height: 16.91217803955078px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-6 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.043909072875977px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.664396286010742px;
    letter-spacing: 0px;
    color: rgba(124, 155, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-555 .f2h-text-7 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 12.043909072875977px;
    text-decoration: none;
    text-transform: none;
    line-height: 17.664396286010742px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }

  #f2h-frame-300 {
    position: relative;
    overflow: hidden;
    display: none;
  }

  #f2h-frame-300 p {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 7.222476959228516px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.415968894958496px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-0 {
    font-family: Lato;
    font-style: normal;
    font-weight: 800;
    font-size: 9.860501289367676px;
    text-decoration: none;
    text-transform: none;
    line-height: normal;
    letter-spacing: 0px;
    color: rgba(0, 0, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-2 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 6.419980049133301px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.415968894958496px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-3 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 6.419980049133301px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.415968894958496px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-4 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 6.419980049133301px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.415968894958496px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-5 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 6.419980049133301px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.415968894958496px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-6 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 6.7055277824401855px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.834771156311035px;
    letter-spacing: 0px;
    color: rgba(124, 155, 0, 1);
    mix-blend-mode: normal;
  }
  #f2h-frame-300 .f2h-text-7 {
    font-family: Lato;
    font-style: normal;
    font-weight: 400;
    font-size: 6.7055277824401855px;
    text-decoration: none;
    text-transform: none;
    line-height: 9.834771156311035px;
    letter-spacing: 0px;
    color: rgba(33, 33, 33, 1);
    mix-blend-mode: normal;
  }
</style>
